using Xunit;

namespace Hertzole.UnityToolbox.Generator.Tests;

public sealed partial class SubscribeMethodsGeneratorTests
{
	private const string SCRIPTABLE_BOOL_STRUCT = /*lang=cs*/@"using Hertzole.UnityToolbox;
using Hertzole.ScriptableValues;
 
public partial struct TestStruct
{
 	[GenerateSubscribeMethods]
 	public ScriptableBool boolValue;
	[GenerateSubscribeMethods]
	public ScriptableBool BoolValue { get; set; }
    
    private partial void OnBoolValueChanged(bool previousValue, bool newValue)
	{
		throw new NotImplementedException();
	}
}";

	private const string SCRIPTABLE_VALUE_T_STRUCT = /*lang=cs*/@"using Hertzole.UnityToolbox;
using Hertzole.ScriptableValues;
 
public partial struct TestStruct
{
 	[GenerateSubscribeMethods]
 	public ScriptableValue<bool> value;
	[GenerateSubscribeMethods]
	public ScriptablValue<bool> Value { get; set; }
    
    private partial void OnValueChanged(bool previousValue, bool newValue)
	{
		throw new NotImplementedException();
	}
}";

	private const string SCRIPTABLE_EVENT_STRUCT = /*lang=cs*/@"using Hertzole.UnityToolbox;
using Hertzole.ScriptableValues;

public partial struct TestStruct
{
    [GenerateSubscribeMethods]
    public ScriptableEvent eventValue;
    [GenerateSubscribeMethods]
    public ScriptableEvent EventValue { get; set; }
    
    private partial void OnEventInvoked()
	{
		throw new NotImplementedException();
	}
}";

	private const string SCRIPTABLE_BOOL_EVENT_STRUCT = /*lang=cs*/@"using Hertzole.UnityToolbox;
using Hertzole.ScriptableValues;

public partial struct TestStruct
{
	[GenerateSubscribeMethods]
	public ScriptableBoolEvent boolEvent;
	[GenerateSubscribeMethods]
	public ScriptableBoolEvent BoolEvent { get; set; }
	
	private partial void OnBoolEventInvoked(bool value)
	{
		throw new NotImplementedException();
	}
}";

	private const string SCRIPTABLE_EVENT_T_STRUCT = /*lang=cs*/@"using Hertzole.UnityToolbox;
using Hertzole.ScriptableValues;

public partial struct TestStruct
{
    	[GenerateSubscribeMethods]
    	public ScriptableEvent<bool> eventValue;
    	[GenerateSubscribeMethods]
    	public ScriptableEvent<bool> EventValue { get; set; }
    
    	private partial void OnEventInvoked(bool value)
        {
			throw new NotImplementedException();
		}
}";

	private const string EXPECTED_SCRIPTABLE_BOOL_STRUCT = /*lang=cs*/@"// <auto-generated>
// 		This file was generated by the Unity Toolbox Generator, by Hertzole.
// 		Do not edit this file manually
// </auto-generated>

partial struct TestStruct
{
	private bool hasSubscribedToBoolValue = false;

	private void SubscribeToAllScriptableValues()
	{
		SubscribeToBoolValue();
	}

	private void UnsubscribeFromAllScriptableValues()
	{
		UnsubscribeFromBoolValue();
	}

	private void SubscribeToBoolValue()
	{
		if (boolValue != null && !hasSubscribedToBoolValue)
		{
			boolValue.OnValueChanged += OnBoolValueChanged;
			hasSubscribedToBoolValue = true;
		}
	}

	private void UnsubscribeFromBoolValue()
	{
		if (boolValue != null && hasSubscribedToBoolValue)
		{
			boolValue.OnValueChanged -= OnBoolValueChanged;
			hasSubscribedToBoolValue = false;
		}
	}

	private partial void OnBoolValueChanged(bool previousValue, bool newValue);
}
";

	private const string EXPECTED_SCRIPTABLE_VALUE_T_STRUCT = /*lang=cs*/@"// <auto-generated>
// 		This file was generated by the Unity Toolbox Generator, by Hertzole.
// 		Do not edit this file manually
// </auto-generated>

partial struct TestStruct
{
	private bool hasSubscribedToValue = false;

	private void SubscribeToAllScriptableValues()
	{
		SubscribeToValue();
	}

	private void UnsubscribeFromAllScriptableValues()
	{
		UnsubscribeFromValue();
	}

	private void SubscribeToValue()
	{
		if (value != null && !hasSubscribedToValue)
		{
			value.OnValueChanged += OnValueChanged;
			hasSubscribedToValue = true;
		}
	}

	private void UnsubscribeFromValue()
	{
		if (value != null && hasSubscribedToValue)
		{
			value.OnValueChanged -= OnValueChanged;
			hasSubscribedToValue = false;
		}
	}

	private partial void OnValueChanged(bool previousValue, bool newValue);
}
";

	private const string EXPECTED_SCRIPTABLE_EVENT_STRUCT = /*lang=cs*/@"// <auto-generated>
// 		This file was generated by the Unity Toolbox Generator, by Hertzole.
// 		Do not edit this file manually
// </auto-generated>

partial struct TestStruct
{
	private bool hasSubscribedToEventValue = false;

	private void SubscribeToAllScriptableValues()
	{
		SubscribeToEventValue();
	}

	private void UnsubscribeFromAllScriptableValues()
	{
		UnsubscribeFromEventValue();
	}

	private void SubscribeToEventValue()
	{
		if (eventValue != null && !hasSubscribedToEventValue)
		{
			eventValue.OnInvoked += OnEventValueInvoked;
			hasSubscribedToEventValue = true;
		}
	}

	private void UnsubscribeFromEventValue()
	{
		if (eventValue != null && hasSubscribedToEventValue)
		{
			eventValue.OnInvoked -= OnEventValueInvoked;
			hasSubscribedToEventValue = false;
		}
	}

	private partial void OnEventValueInvoked(object sender, global::System.EventArgs e);
}
";

	private const string EXPECTED_SCRIPTABLE_BOOL_EVENT_STRUCT = /*lang=cs*/@"// <auto-generated>
// 		This file was generated by the Unity Toolbox Generator, by Hertzole.
// 		Do not edit this file manually
// </auto-generated>

partial struct TestStruct
{
	private bool hasSubscribedToBoolEvent = false;

	private void SubscribeToAllScriptableValues()
	{
		SubscribeToBoolEvent();
	}

	private void UnsubscribeFromAllScriptableValues()
	{
		UnsubscribeFromBoolEvent();
	}

	private void SubscribeToBoolEvent()
	{
		if (boolEvent != null && !hasSubscribedToBoolEvent)
		{
			boolEvent.OnInvoked += OnBoolEventInvoked;
			hasSubscribedToBoolEvent = true;
		}
	}

	private void UnsubscribeFromBoolEvent()
	{
		if (boolEvent != null && hasSubscribedToBoolEvent)
		{
			boolEvent.OnInvoked -= OnBoolEventInvoked;
			hasSubscribedToBoolEvent = false;
		}
	}

	private partial void OnBoolEventInvoked(object sender, bool args);
}
";

	private const string EXPECTED_SCRIPTABLE_EVENT_T_STRUCT = /*lang=cs*/@"// <auto-generated>
// 		This file was generated by the Unity Toolbox Generator, by Hertzole.
// 		Do not edit this file manually
// </auto-generated>

partial struct TestStruct
{
	private bool hasSubscribedToEventValue = false;

	private void SubscribeToAllScriptableValues()
	{
		SubscribeToEventValue();
	}

	private void UnsubscribeFromAllScriptableValues()
	{
		UnsubscribeFromEventValue();
	}

	private void SubscribeToEventValue()
	{
		if (eventValue != null && !hasSubscribedToEventValue)
		{
			eventValue.OnInvoked += OnEventValueInvoked;
			hasSubscribedToEventValue = true;
		}
	}

	private void UnsubscribeFromEventValue()
	{
		if (eventValue != null && hasSubscribedToEventValue)
		{
			eventValue.OnInvoked -= OnEventValueInvoked;
			hasSubscribedToEventValue = false;
		}
	}

	private partial void OnEventValueInvoked(object sender, bool args);
}
";

	[Fact]
	public void Struct_ScriptableBool()
	{
		GeneratorTest.RunTest<SubscribeMethodsGenerator>("TestStruct.ScriptableValueSubscriptions.g.cs", SCRIPTABLE_BOOL_STRUCT,
			EXPECTED_SCRIPTABLE_BOOL_STRUCT);
	}

	[Fact]
	public void Struct_ScriptableValueT()
	{
		GeneratorTest.RunTest<SubscribeMethodsGenerator>("TestStruct.ScriptableValueSubscriptions.g.cs", SCRIPTABLE_VALUE_T_STRUCT,
			EXPECTED_SCRIPTABLE_VALUE_T_STRUCT);
	}

	[Fact]
	public void Struct_ScriptableEvent()
	{
		GeneratorTest.RunTest<SubscribeMethodsGenerator>("TestStruct.ScriptableValueSubscriptions.g.cs", SCRIPTABLE_EVENT_STRUCT,
			EXPECTED_SCRIPTABLE_EVENT_STRUCT);
	}

	[Fact]
	public void Struct_ScriptableBoolEvent()
	{
		GeneratorTest.RunTest<SubscribeMethodsGenerator>("TestStruct.ScriptableValueSubscriptions.g.cs", SCRIPTABLE_BOOL_EVENT_STRUCT,
			EXPECTED_SCRIPTABLE_BOOL_EVENT_STRUCT);
	}

	[Fact]
	public void Struct_ScriptableEventT()
	{
		GeneratorTest.RunTest<SubscribeMethodsGenerator>("TestStruct.ScriptableValueSubscriptions.g.cs", SCRIPTABLE_EVENT_T_STRUCT,
			EXPECTED_SCRIPTABLE_EVENT_T_STRUCT);
	}
}