plugins:
  - '@semantic-release/github'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/commit-analyzer'
  - - '@semantic-release/exec'
    - prepareCmd: "sed -i -e '/AssemblyVersion/s/\".*\"/\"${nextRelease.version}\"/' 
        Packages/se.hertzole.unitytoolbox/Runtime/AssemblyInfo.cs
        Packages/se.hertzole.unitytoolbox/Editor/AssemblyInfo.cs
        Generator/Hertzole.UnityToolbox.Generator/AssemblyInfo.cs"
  - - '@semantic-release/changelog'
    - changelogFile: 'Packages/se.hertzole.unitytoolbox/CHANGELOG.md'
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: "Packages/se.hertzole.unitytoolbox"
  - - '@semantic-release/git'
    - assets:
        - 'Packages/se.hertzole.unitytoolbox/Runtime/AssemblyInfo.cs'
        - 'Packages/se.hertzole.unitytoolbox/Editor/AssemblyInfo.cs'
        - 'Generator/Hertzole.UnityToolbox.Generator/AssemblyInfo.cs'
        - 'Packages/se.hertzole.unitytoolbox/package.json'
        - 'Packages/se.hertzole.unitytoolbox/CHANGELOG.md'