name: Test and Build

on:
  push:
    branches: [master]
    paths:
      - 'Generator/**'
      - 'Assets/**'
      - 'Packages/**'
      - '.github/workflows/**'
      - '.releaserc.yml'

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  generator:
    name: Test and Build Generator
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-6000.0.25f1-base-3.1.0
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Safe repo
        run: git config --global --add safe.directory /__w/unity-toolbox/unity-toolbox

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: LibraryFolder
          restore-keys: |
            LibraryFolder

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x

      - name: Build Generator
        run: |
          cd Generator
          dotnet publish -c Release -o ../GeneratorBuild
          cd ..

      - name: Setup Unity
        continue-on-error: true
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "$UNITY_LICENSE" | tr -d '\r' > License.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile License.ulf -quit 
          unity-editor -nographics -logFile /dev/stdout -customBuildName unity-toolbox -projectPath . -executeMethod GitTools.Solution.Sync -quit

      - name: Test Generator
        run: |
          cd Generator
          dotnet test

  unity:
    name: Test and Build Unity Package
    runs-on: ubuntu-latest
    needs: generator
    container: unityci/editor:ubuntu-6000.0.25f1-base-3.1.0
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Safe repo
        run: git config --global --add safe.directory /__w/unity-toolbox/unity-toolbox

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: LibraryFolder
          restore-keys: |
            LibraryFolder
      
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x

      - name: Build Generator
        run: |
          cd Generator
          dotnet publish -c Release
          cd ..

      - name: Setup Unity
        continue-on-error: true
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        run: |
          echo "$UNITY_LICENSE" | tr -d '\r' > License.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile License.ulf -quit 
          unity-editor -nographics -logFile /dev/stdout -customBuildName unity-toolbox -projectPath . -executeMethod GitTools.Solution.Sync -quit

      # - name: Run Play Mode Tests
      #   run: unity-editor -nographics -logFile /dev/stdout -runTests -testPlatform playmode -testResults Tests/playmode.xml -enableCodeCoverage -coverageResultsPath TestCoverage -debugCodeOptimization -coverageOptions "generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+Hertzole.UnityToolbox"

      # - name: Release
      #   id: semantic
      #   uses: cycjimmy/semantic-release-action@v3
      #   with:
      #     extra_plugins: |
      #       @semantic-release/exec
      #       @semantic-release/changelog
      #       @semantic-release/git
      #     branch: master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Package Branch
        run: |
          git branch -d package &> /dev/null || echo package branch not found
          git subtree split -P "$PKG_ROOT" -b package
          if [[ -d "Assets/Samples" ]]; then
            mv "Assets/Samples" /tmp/example
          fi
          if [[ -f "README.md" ]]; then
            mv README.md /tmp/README.md
          fi
          echo "ROOT!"
          ls
          echo "PACKAGES!"
          ls Packages
          echo "PACKAGE!"
          ls Packages/se.hertzole.unitytoolbox
          echo "PLUGINS!"
          git branch
          ls -l Packages/se.hertzole.unitytoolbox/Plugins
          mv ./Packages/se.hertzole.unitytoolbox/Plugins/Hertzole.UnityToolbox.Generator.dll /tmp/Generator.dll
          mv ./Packages/se.hertzole.unitytoolbox/Plugins/Hertzole.UnityToolbox.Analyzers.dll /tmp/Analyzers.dll
          mv ./Packages/se.hertzole.unitytoolbox/Plugins/Hertzole.UnityToolbox.Shared.dll /tmp/Shared.dll
          git checkout package
          if [[ -d "/tmp/example" ]]; then
            mkdir "Samples~"
            mv /tmp/example/* "Samples~/"
            git add "Samples~"
          fi
          if [[ -f "/tmp/README.md" ]]; then
            mv /tmp/README.md README.md
            git add README.md
          fi
          if [[ -d "Tests" ]]; then
            rm -rf Tests
            rm -f Tests.meta
          fi
          mv /tmp/Generator.dll ./Plugins/Hertzole.UnityToolbox.Generator.dll 
          mv /tmp/Analyzers.dll ./Plugins/Hertzole.UnityToolbox.Analyzers.dll 
          mv /tmp/Shared.dll ./Plugins/Hertzole.UnityToolbox.Shared.dll 
          git add Plugins/Hertzole.UnityToolbox.Generator.dll
          git add Plugins/Hertzole.UnityToolbox.Analyzers.dll
          git add Plugins/Hertzole.UnityToolbox.Shared.dll
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "Packaged project"
          git push -f -u origin package
        env:
          PKG_ROOT: "Packages/se.hertzole.unitytoolbox"
        shell: bash

      # - name: Create Release Tag
      #   if: steps.semantic.outputs.new_release_published == 'true'
      #   run: |
      #     git tag $TAG package
      #     git push origin --tags
      #   env:
      #     TAG: package/v${{ steps.semantic.outputs.new_release_version }}
